version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PW
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:5432"
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
    ports:
      - "$SERVER_PORT:8080"
    links:
      - postgres

  migrate:
    build:
      dockerfile: migrate.Dockerfile
    command: tail -F anything
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=$POSTGRES_HOST port=$POSTGRES_PORT user=$POSTGRES_USER password=$POSTGRES_PW dbname=$POSTGRES_DB
    volumes:
      - ./db/migrations:/migrations
    links:
      - postgres
volumes:
  postgres-data:
